image: docker:latest
services:
  - name: docker:dind
    command:
      [
        '--insecure-registry=http://127.0.0.1.nip.io:8888',
      ]

stages:
  - build
  - release

variables:
  BUILD_IMAGE: http://127.0.0.1.nip.io:8888/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  RELEASE_IMAGE: http://127.0.0.1.nip.io:8888/$CI_PROJECT_PATH:latest
  GIT_CURL_VERBOSE: 1
  GIT_TRACE: 1
  DOCKER_TLS_CERTDIR: ''
  
build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN http://127.0.0.1.nip.io:8888
    - docker build --pull -t prod-image:latest .
    - docker tag release:latest 127.0.0.1.nip.io:8888/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
    - docker push $BUILD_IMAGE
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH =~ /^release\/*/  || $CI_COMMIT_BRANCH == "main"'
      when: always
    
release:
  stage: release
  script:
    - docker pull $BUILD_IMAGE
    - docker tag $BUILD_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH =~ /^release\/*/  || $CI_COMMIT_BRANCH == "main"'
      when: always
